namespace CRM.Operation.Enums
{
    public enum QueueItemType
    {
        /// <summary>
        /// Invalid item type
        /// </summary>
        None = 0,

        /// <summary>
        /// Message for SMS service
        /// </summary>
        SmsMessage = 1,

        /// <summary>
        /// Message for PolicySigning service
        /// </summary>
        //[System.Obsolete("Make unified policy signing type for Cmtpl, Travel, etc...")]
        CmtplPolicySigning = 2,

        /// <summary>
        /// Cmtpl invoice export to the GPP through the bank service.
        /// </summary>
        GPPExport = 3,

        /// <summary>
        /// Message for Email
        /// </summary>
        Email = 4,

        /// <summary>
        /// PreIssued policy activation when invoice was paid
        /// </summary>
        PolicyActivation = 5,

        //[System.Obsolete("Make unified policy signing type for Cmtpl, Travel, etc...")]
        TravelPolicySigning = 6,

        CmtplSupplementPolicySigning = 10,

        /// <summary>
        /// When ISB sends us some requests, but we have failed to process them, we should schedule it's repeated execution attempts, 
        /// as ISB will not send it once again
        /// </summary>
        FailedWebApiRequests = 7,

        ///<summary>
        /// Change mediator (seller) of policy issued by ISB via WebIms after issue 
        /// </summary>
        IsbContractUpdate = 8,

        OperatorExport = 9,
        //TokenCorrelation = 9
        CRM = 10
    }

    public enum QueueItemSubtype
    {
        /// <summary>
        /// Invalid item type
        /// </summary>
        None = 0,

        // SmsMessage subtypes
        SmsMessagePolicyIssue = 100,
        SmsMessagePolicyCancel = 101,
        SmsMessagePolicyTerminate = 102,

        // PolicySigning subtypes
        PrimarySigning = 200,

        // Subtypes for GPP export
        GPPStandardExport = 300,

        // Email subtypes
        EmailWithoutAttachment = 400,
        EmailPolicyIssueCmtpl = 401,
        EmailPolicyIssueTravel = 402,
        EmailPolicyIssueTravelWithRulesAttachment = 403,
        EmailPolicyIssueCmtplSupplementYellow = 404,
        EmailPolicyIssueCmtplSupplementOrange = 405,
        EmailPolicyIssueWithAttachment = 406,
        EmailInvoiceWithAttachment = 407,
        EmailPolicyIssueProperty = 408,
        EmailSuspeciousActivity = 416,
        //PolicyActivation
        StandardActivation = 500,


        //FailedWebApiRequests
        FailedWebApiRequestsCmtplContract = 701,
        FailedWebApiRequestsPayment = 702,
        FailedWebApiRequestsStatusChange = 703,
        FailedWebApiRequestsTerminate = 704,
        FailedWebApiRequestsSign = 705,

        // Local token generated by policy main data
        ByPolicyIdentificationHashCmtpl = 801,
        ByPolicyIdentificationHashPa = 802,

        //Types of Action for ISB policy
        PolicyIssue = 900,
        PolicyVehicleChange = 901,
        PolicyCancellation = 902,
        PolicyTermination = 903,


        //Client data
        ClientCreateOrUpdate = 904
    }

    public enum QueueItemStatus
    {
        /// <summary>
        /// None / Not set
        /// </summary>
        None = 0,

        /// <summary>
        /// Message is put into the queue and is available for processing
        /// </summary>
        Ready = 1,

        /// <summary>
        /// Message was processed, but failed. Maximal retry count exceed and processing will retry later.
        /// </summary>
        Retry = 2,

        /// <summary>
        /// Maximal retry count is reached and system will not try to process message anymore. Message is ready to be deleted from the queue
        /// </summary>
        Failed = 3,

        /// <summary>
        /// Message is processed successfully and is ready to be deleted from the queue
        /// </summary>
        Processed = 4
    }
    /*
     None
      |               +----+
      \/             \/    |
     Ready ------> Retry --+
      |             /| 
      +------------/ |
      |              |
      \/             \/
   Processed       Failed

     */
}
